# Workflow to check code quality and complexity

name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install radon
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Code complexity
      run: |
        # Runs Radon quality check
        radon cc python --total-average --show-complexity
    - name: Code quality with flake8
      run: |
        # Runs code quality check
        flake8 python --exit-zero --count --statistics --max-complexity=10
